// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQzDt9N3yyp7ydZDyna0wPFSFHnsRKMI',
    appId: '1:737843945170:web:b63f65cfd7c4a0cbb8970b',
    messagingSenderId: '737843945170',
    projectId: 'cardstore-6cd62',
    authDomain: 'cardstore-6cd62.firebaseapp.com',
    storageBucket: 'cardstore-6cd62.firebasestorage.app',
    measurementId: 'G-LGX6TDWG1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbiQWSzPKakJs5u2Uuh5337220B2iD1BA',
    appId: '1:737843945170:android:fea1cba9ddad1c23b8970b',
    messagingSenderId: '737843945170',
    projectId: 'cardstore-6cd62',
    storageBucket: 'cardstore-6cd62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiIiMSsv-iNjkLoEH459VLqSDgU8jQXxk',
    appId: '1:737843945170:ios:1eecb5e9498ffd1bb8970b',
    messagingSenderId: '737843945170',
    projectId: 'cardstore-6cd62',
    storageBucket: 'cardstore-6cd62.firebasestorage.app',
    iosBundleId: 'com.example.afitnessgym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiIiMSsv-iNjkLoEH459VLqSDgU8jQXxk',
    appId: '1:737843945170:ios:1eecb5e9498ffd1bb8970b',
    messagingSenderId: '737843945170',
    projectId: 'cardstore-6cd62',
    storageBucket: 'cardstore-6cd62.firebasestorage.app',
    iosBundleId: 'com.example.afitnessgym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnQzDt9N3yyp7ydZDyna0wPFSFHnsRKMI',
    appId: '1:737843945170:web:6b04ad7e50f20019b8970b',
    messagingSenderId: '737843945170',
    projectId: 'cardstore-6cd62',
    authDomain: 'cardstore-6cd62.firebaseapp.com',
    storageBucket: 'cardstore-6cd62.firebasestorage.app',
    measurementId: 'G-NJJQ067NW0',
  );
}
